import Cartridge from './cartridge';
import Bootrom from './bootrom';
import Memory from './memory';
import CPU from './cpu';
import PPU from './ppu';
import APU from './apu';
import Controller from './controller';
import LinkCable from './linkcable';
import CYCLES from './cycles';
import INTERRUPTS from './interrupts';
import DebugEngine from './tools/DebugEngine';
import TIMER from './timer';

export const memory = new Memory();
export const bootrom = new Bootrom();
export const cpu = new CPU();
export const ppu = new PPU();
export const apu = new APU();
export const controller = new Controller();
export const linkcable = new LinkCable();
export const cycles = new CYCLES();
export const cartridge = new Cartridge();
export const interrupts = new INTERRUPTS();
export const timer = new TIMER();
export const debugengine = new DebugEngine();
